### ISSUE TITLE
[Merged on GitLab] Rename & move fusion files around to get rid of core & utils

### ISSUE THREAD

**Issue by sf-chris** [Sportsflare/bass-tube#153]
Rename some vaguely named folders that we better understand now that the code is written :wink:

*Originally created on GitLab as an MR by steffansafey (https://gitlab.com/sportsflare/real-time/bass-tube/-/merge_requests/22) on 2022-03-16T00:23:05.328Z*

**Comment by sf-chris** [comment]
Ty G

*Originally commented on GitLab by steffansafey on 2022-03-16T00:51:12.156Z*

**Comment by sf-chris** [comment]
LGTM bro

*Originally commented on GitLab by matt.cavill on 2022-03-16T00:42:27.477Z*

**Comment by sf-chris** [comment]
Yeah that makes sense actually, can think of a general file name for those functions in the mean time.

*Originally commented on GitLab by matt.cavill on 2022-03-16T00:42:01.452Z*

**Comment by sf-chris** [comment]
FWIW, I think `general` would be appropriate here if we were fusing more than fixtures (`coalesce` and `collect` aren't fixture-specific)

But we're not yet, so will make it a single file

*Originally commented on GitLab by steffansafey on 2022-03-16T00:38:03.239Z*

**Comment by sf-chris** [comment]
I'll just move it into fixtures

*Originally commented on GitLab by steffansafey on 2022-03-16T00:33:08.705Z*

**Comment by sf-chris** [comment]
Is `general` better than `core` tho?

*Originally commented on GitLab by matt.cavill on 2022-03-16T00:31:45.075Z*

**Comment by sf-chris** [comment]
Just 4 u @sadboy

*Originally commented on GitLab by steffansafey on 2022-03-16T00:23:15.374Z*

**Comment by sadboy** [comment]
Hi there! Just a heads up that I think you're tagging the wrong person :) (@sadboy is me)
